### ISSUE TITLE
Crew Member -Delete

### ISSUE THREAD

**Issue by rtate2** [nss-evening-cohort-10/nutshell-panam-airlines#11]
# User Story
As a user, I should be able to remove a crew member from the team.

# Acceptance Criteria
**GIVEN** the user is logged in and visits the crew page
**WHEN** the user clicks button "x" on the crew member card
**THEN** the crew member is removed from firebase
**AND** update the DOM

# Dev Notes
• Create an axios call in the helpers/data/crewData.js (removeCrewMember) file that allows user to delete crew members from Firebase and the DOM (axios.delete)
• Create a button "x" that prints to every individual crew member card, located at the top right and will have the ID of the crewmember as the Id of the button. This button will only delete the crew member card associated. The button should have an event listener that reads the crewId from the button, and deletes the individual crew member from firebase.
• The deleteCrewMember eventlistener will call the removeCrewMember function to target the data within Firebase and delete it
- Call createCrewMembers to update the dom when the delete is successful in the .then of the removeCrewMember call

**Comment by rtate2** [comment]
**Card profile w/ delete button located on top right of card**
<img width="297" alt="PanAm-Crew-singleCardView" src="https://user-images.githubusercontent.com/54008854/68994779-6566e400-084c-11ea-95f4-8f38071ddc4d.png">

**Comment by michaelclark2** [comment]
I don't want a feature to delete all employees, let's nix that feature.  And I don't want there to be two categories of crew members, as mentioned in other comments.
