### ISSUE TITLE
Plane-Read

### ISSUE THREAD

**Issue by rarceneaux** [nss-evening-cohort-10/nutshell-panam-airlines#12]
# User Story

- As a user, I should be able to view all the planes PanAm owns.

# Dev Notes

- Create ra-planeSetUp branch in VS Code
- Create `planeData.js` file in `src/javascripts/helpers/data` folder to create new promise `axios.get()`
- Create `plane` component in the `src/javascipts/components` folder
                  -Make a `plane.js` and `plane.scss` file
- Create `planeCard` component in the `src/javascipts/components` folder
                  -Make a `planeCard.js` and `planeCard.scss` file which will build the string builder to print the planes to the `plane` div in the index.html. There will be a max of 3 cards per row.

# AC
**WHEN** the user visits the `Fleet Inventory & Maintenance` dashboard 
**THEN**they will see (3)  plane cards in a row `d-flex` printed in the `plane` div in the index.html   (See Wireframe Below)
<img width="717" alt="Screen Shot 2019-11-14 at 9 30 45 PM" src="https://user-images.githubusercontent.com/40898992/68915049-2cccea80-0726-11ea-84bf-86ef7b6f632f.png">

**Comment by rarceneaux** [comment]
Plane ERD Overview

<img width="227" alt="Screen Shot 2019-11-13 at 9 11 27 AM" src="https://user-images.githubusercontent.com/40898992/68776329-871a5e00-05f5-11ea-9173-55129ed70ace.png">

**Comment by rarceneaux** [comment]
<img width="485" alt="Screen Shot 2019-11-13 at 11 53 23 AM" src="https://user-images.githubusercontent.com/40898992/68791024-116ebc00-060e-11ea-8574-e5485b6eb542.png">

**Comment by rarceneaux** [comment]
```
{
  "plane1": {
    "team": " string teamA",
    "airport": "string BNA",
    "planeNum": "string w/ Numbers AB850",
    "modelType": "string w/ Number Boeing 737",
    "capacity": number 150,
  }
```

**Comment by rarceneaux** [comment]
<img width="244" alt="Screen Shot 2019-11-13 at 12 22 55 PM" src="https://user-images.githubusercontent.com/40898992/68794826-5fd38900-0615-11ea-978a-17c0aeec0932.png">

**Comment by michaelclark2** [comment]
Looks good, i would move the stuff about seeding the database into it's own ticket.  you could also do all the seed data at once now that you've all decided what the ERD is going to be and what values are in each datapoint.

**Comment by rarceneaux** [comment]
Speak with group about renaming type to modelType to reflect how planes are named in real world

**Comment by michaelclark2** [comment]
Keep in mind that the user can read no matter if they are logged in or not, and include more notes about how the cards will look and be displayed to the page: what div will you print to?  how many cards will fit in a row?
