### ISSUE TITLE
ERD

### ISSUE THREAD

**Issue by ghost** [nss-evening-cohort-10/nutshell-panam-airlines#13]
# User Story
As a developer I need a rough ERD to use as an outline to the data for each module that I will be accessing, and how those data points link up.

# AC
**WHEN** I reference the ERD
**THEN** I should be able to clearly see what data points are necessary when building each module

# Dev Notes
StartingERD:
<img width="856" alt="Screen Shot 2019-11-13 at 7 31 07 PM" src="https://user-images.githubusercontent.com/51291392/68819190-f53e3f80-064c-11ea-9e7a-aa0dc4ffe9c9.png">

StretchERD:
<img width="490" alt="chestnutStretchERD" src="https://user-images.githubusercontent.com/54124397/68776869-6272b600-05f6-11ea-9410-b10ab9961609.PNG">

**Comment by rtate2** [comment]
# crewDataStructure
<img width="190" alt="PanAm-Crew-dataStructure" src="https://user-images.githubusercontent.com/54008854/68820107-e4db9400-064f-11ea-8fbf-967a8e982a62.png">
