### ISSUE TITLE
Plane- Create

### ISSUE THREAD

**Issue by rarceneaux** [nss-evening-cohort-10/nutshell-panam-airlines#14]
# User Story

- As a user, I should be able to add a new plane to the PanAm fleet inventory 
<img width="271" alt="Screen Shot 2019-11-15 at 7 04 01 AM" src="https://user-images.githubusercontent.com/40898992/68946091-b8229c00-0777-11ea-922f-4827930430e4.png">
After the uses makes their input selects and press the SAVE button the new plane will appear on the page.

# Dev Notes 

- Create a ra-createPlane branch
- Make addNewPlane function in planeData.js file `axios.post()` 
- Import the addNewPlane function into the plane.js file
- Create addNewPlane function in plane.js file that includes `Add Plane` button element in domString 
- Create Event listener on the `Add Plane` button that will present the modal popup 
- Call the buildPlane function to reflect the addition of the new plane

# AC
**When** the user clicks the  `Add Plane` button the modal will display on page
**THEN** the user will see the corresponding input fields with labels to type in the plane values into the modal form
**THEN** the user will press the `save` button and `close` within the modal that will run  the addNewPlane function
**AND** the new plane card will appear on the dom in the `planes` div with the existing  planes in the fleet
**AND** the created plane will be added to the planes collection in firebase

**Comment by rarceneaux** [comment]
<img width="244" alt="Screen Shot 2019-11-13 at 12 22 55 PM" src="https://user-images.githubusercontent.com/40898992/68792176-76c3ac80-0610-11ea-833a-621d9182a6b0.png">

**Comment by rarceneaux** [comment]
<img width="485" alt="Screen Shot 2019-11-13 at 11 53 23 AM" src="https://user-images.githubusercontent.com/40898992/68792207-80e5ab00-0610-11ea-89b7-da3c74bd5124.png">

**Comment by michaelclark2** [comment]
This one is good, I would expand on how the form will be displayed on the dom.  is it a modal?  or another card in the view?  Also, put in the dev notes where your component is going to be named and the files that need to be created

**Comment by rarceneaux** [comment]
**ADD NEW PLANE MODAL VIEW**

<img width="271" alt="Screen Shot 2019-11-15 at 7 04 01 AM" src="https://user-images.githubusercontent.com/40898992/68945605-5f063880-0776-11ea-8a7d-1899572bed00.png">

**Comment by rarceneaux** [comment]
<img width="717" alt="Screen Shot 2019-11-14 at 9 30 45 PM" src="https://user-images.githubusercontent.com/40898992/68946723-477c7f00-0779-11ea-9b00-cd476e91dd60.png">
