### ISSUE TITLE
Airport read

### ISSUE THREAD

**Issue by John-Ryan-Johnson** [nss-evening-cohort-10/nutshell-panam-airlines#15]
**User Story**
As a user, I should be able to view all the airports PanAm uses.

**AC**

**WHEN** the user visits the Airports page
**THEN** I should be able to view all of the airports
**AND**   there will be 3 in a row, and they will follow the mockups

**Dev Notes** 
1. Create airportsData.js in javascripts/helpers/data and create an axios call getAllAirports promise to get the data imported and turn object of arrays to an array - see seed data ticket for example
2.  Create airports folder component within javascripts/components and include airports.js and airports.scss, be sure to link the js and scss
i). In airports.js create a createAirportCard function that calls the getAllAirports and runs it through a forEach loop and create bootstrap cards; this will print out to the airports div within the html - this will be printed to the DOM upon page load using printToDom
ii) If the userobject is found with firebase.auth().currentUser, then add the edit and delete buttons to the domstring. use this snippet in createAirportCard

const user = firebase.auth().currentUser;
if (user != null) {
 // do stuff
}
3. **Styling**
        * "Airports" centered as H1 tag on page Load
        *  Background image of PanAm image which spans the entire screen
        * Cards spaced evenly centered in the page under the title, maximum of three per row

![Pan Am Create moqup](https://user-images.githubusercontent.com/51214463/68899802-10b25480-06f8-11ea-9626-4030c1c8028b.PNG)

**Comment by michaelclark2** [comment]
This one's coming along, looks like youre currently working on this so keep it up!  keep in mind that the user can read no matter if they are logged in, they can only create, update, and delete when they are logged in
