### ISSUE TITLE
Airport create

### ISSUE THREAD

**Issue by John-Ryan-Johnson** [nss-evening-cohort-10/nutshell-panam-airlines#16]
**User Story**
As a user I should be able to add airports as needed.

**AC**

**GIVEN** the user is logged in and visits the Airports page
**WHEN** they click the "Add " button
**THEN** there will be a modal to create a new airport

**WHEN** the "save" button is clicked
**THEN** the new user will be found in airports collection in firebase
**AND** the dom will be updated from firebase

**Dev Notes**

*  Create an axios call in the airportsData.js (addNewAirport) file that allows user to post the object to firebase (post)
* addNewAirport will take a airport object as a parameter
*  Create the "Add" button below the card that prepopulates a modal in index.html for the user to input information to create a new airport within the specific category
*  Create addAirport function within components/Airports/airports.js that reads the values from the input fields to create a new airport object, and then pass the object to addNewAirport
*  update dom with createAirportCard function

**Styling**
*  The card styling will be the same within a bootstrap card

![Pan Am Add moqup](https://user-images.githubusercontent.com/51214463/68899666-c92bc880-06f7-11ea-997a-ca08cd7297d6.PNG)

**Comment by michaelclark2** [comment]
This one is better, expand on how the form will display on the dom,  are you thinking of a modal, or what?
Also, in your dev notes, you should talk about where you are going to write the event listeners, when are you going to attach the event listeners, and if you are going to make any new components, you should name them and include the files you are going to create for them

**Comment by michaelclark2** [comment]
let's make the international just one checkbox instead of two checkboxes for true and false.  you can see if something is true or false with one checkbox, otherwise, this one is good
