### ISSUE TITLE
Part 2: Airport - Update

### ISSUE THREAD

**Issue by John-Ryan-Johnson** [nss-evening-cohort-10/nutshell-panam-airlines#17]
**User Story**
As a user, I should be able to edit an airport.

**AC**
**GIVEN** the user is logged in and visits the Airports page
**WHEN** the user clicks the edit button on the card
**THEN** a modal will pop up with prepopulated fields for the airport

**WHEN** the save button is clicked
**THEN** the updated object is sent to firebase
**AND** the dom is updated

**Dev Notes**
* Create an axios call in the airportData.js updateAirport(airportId, airportObj) file that allows user to edit the object by id in firebase (axios.put) URL: ${databaseURL}/crew/$airportId}.json
* to prepopulate the form, get the airport by ID. I need a getAirportById(airportId) function that takes a airportId as a parameter and resolves one single airport object
*  import `updateAirport` into airport.js, and then pass it through a function `updateAirportFromModal` that takes the value of the form inputs on the modal, and creates a new object that will be passed through updateAirport(newAirportObject).
* After the object is edited and the edits are pushed up to firebase via the function above, call the createAirportCard function in the .then of `updateAirportFrom Modal` to reprint the cards on the page
* The function should look like something along the lines of the following:
```
import airportData from '../helpers/data/airportData.js'

const updateAirportFromModal = (e) => {
  const airportId = e.target.whereverYouPlantToAttachTheID;
  const airportObject = {
    imageURL: $('#airport-image-url').val(),
    name: $('#airport-name').val(),
    location: $('#airport-location').val(),
    isInternational: $(whicheverBoxisChecked)
  };
  airportData.updateAirport(airportId, airportObject)
    .then(() => {
      $('#modalID').modal('hide');
      // eslint-disable-next-line no-use-before-define
     createAirportCard();
    })
    .catch((error) => console.error(error));
};
```

* create an event listener that targets the id of the "Save" button from the modal, and calls updateAirportFromModal on click of the "Save" button

![Pan Am Update moqup](https://user-images.githubusercontent.com/51214463/68899846-350e3100-06f8-11ea-8b3c-ccfdd89d103a.PNG)

**Comment by michaelclark2** [comment]
talk more about where you are going to write the event listeners and how the form is gonna be presented to the user.
