### ISSUE TITLE
Airport delete

### ISSUE THREAD

**Issue by John-Ryan-Johnson** [nss-evening-cohort-10/nutshell-panam-airlines#18]
**User Story**
As a user, I should be able to remove an airport.

**AC**

**GIVEN** the user is logged in and visits the airports page
**WHEN** the user clicks "Delete"button on the airport card
**THEN** the airport is removed from firebase
**AND** update the DOM

**Dev Notes**

*   Create a function with an axios call in the helpers/data/airportsData.js (removeAirport) file that allows user to delete airport from Firebase and the DOM (axios.delete)
*  Create a "Delete" button that prints to every individual airport card, located at the bottom and will have the ID of the airport as the Id of the button. This button will only delete the airport card associated. The button should have an event listener that reads the airportId from the button, and deletes the individual airport from firebase.
*  The deleteAirport eventlistener will call the removeAirport function to target the data within Firebase and delete it
*  Call createAirportCard to update the dom when the delete is successful in the .then of the removeAirport call

![Pan Am Delete moqup](https://user-images.githubusercontent.com/51214463/68899915-5242ff80-06f8-11ea-8cf1-401e61d59eeb.PNG)

**Comment by michaelclark2** [comment]
Your AC should include how the dom will be updated, you should just use the function you created to print the airports in the first place.
