### ISSUE TITLE
Plane- Update

### ISSUE THREAD

**Issue by rarceneaux** [nss-evening-cohort-10/nutshell-panam-airlines#22]
# User Story

- As a user, I should be able to edit a plane when I click the edit button on the selected plane card. 

# Dev Notes
- Create ra-updatePlane branch
- Create` axios.put()` in planeData.js file
- Create edit plane function in plane.js file
- Create event listener on the `edit` button in plane.js with the  (e.target.id) will be how I capture 
  the plane object by id from firebase then be able to make the wanted edits within the modal form.
- Create event listener on the `save` button in plane.js this will call the edit plane 
 function and update firebase and the page reflects this change.

# AC
**GIVEN**  a user is  logged in.....
**THEN** a user can click on the `edit` button on a selected plane card  that will call the editPlane
 function in plane.js which presents a modal to edit one or more values of the existing selected plane.
**AND** Firebase reflects the change as well of the edited plane object
**THEN** after they have made the necessary changes clicks the `save` and `close`  button on the modal
**THEN** this updates DOM

**Comment by rarceneaux** [comment]
<img width="245" alt="Screen Shot 2019-11-16 at 10 50 50 AM" src="https://user-images.githubusercontent.com/40898992/68996402-0eb6d580-085f-11ea-935f-4a0e3120271a.png">

**Comment by michaelclark2** [comment]
How will I be able to edit the information?  how is the form going to be present to the user?  After they click the button what happens?  I think youre missing that step in your plan.  And you should not be manipulating the dom, you should update firebase, and then use the same function you use to print the cards the first time to reflect the new changes in firebase.
