### ISSUE TITLE
Food Service-Read

### ISSUE THREAD

**Issue by ghost** [nss-evening-cohort-10/nutshell-panam-airlines#23]
# User Story
As a user, I should be able to view all the food options available for flights.

# AC
**WHEN** the user visits the Food Service tab in the Navbar
**THEN** they should see a div that displays the food.json data for all food options available for each flight

# Dev Notes
* create a foodService component where you will create foodService.js and foodService.scss files
* create foodData.js file under your Data Folder in helpers, where you will import axios along with your apiKeys to pull the food data, in a function similar to the following:
```
import axios from 'axios';
import apiKeys from '../apiKeys.json';

const baseUrl = apiKeys.firebaseKeys.databaseURL;

const getFood = (foodId) => new Promise((resolve, reject) => {
  axios.get(`${baseUrl}/foods.json?orderBy="id"&equalTo="${id}"`)
    .then((response) => {
      const demFoods = response.data;
      const foods = [];
      Object.keys(demFoods).forEach((fdId) => {
        demFoods[fdId].id = fdId;
        foods.push(demFoods[fbId]);
      });
      resolve(foods);// Hard code to return foods
    })
    .catch((error) => reject(error));
});

export default { getfood };
```

* in foodService.js call a function that will use the `getFood` function imported from foodData.js, and create a food card inside a `<div id="foodsModule></div"`  using object literals from your seed data to be placed in your index.html and styled in foodService.scss. `forEach` Food pulled from your seed data, you should see a card printed to the `foodsModule` div in index.html. The function should look like something along the lines of:
```
import './pins.scss';
import $ from 'jquery';
import utilities from '../../helpers/utilities';
import foodData from '../../helpers/data/foodData';

const createFoodCards = () => {
 let domString = '<h1>Food Service</h1>'
 domString += '<div id="foodDivs" class="d-flex flex-wrap">';
  foodData.getFoodData()
    .then((food) => {
      modulesToHide.empty();
      foods.forEach((food) => {
        domString += `
        <div class="card col-4 foodCard card-body"  id="${food.id}">
           <button class="btn btn-danger delete-foodItem"  id="${food.id}" style=" float: 
              right;">X</button>
           <img src="${food.imageURL}" class="card-img-top" alt="..."/>
           <h5 class="card-title" id="food">${food.name}</h5>
            <p>${food.price}</p>
            <p>${food.calories} Cals</p>
            <p>${food.categoryType}</p>
            <button type="button" class="btn btn-success" data-toggle="modal" data- 
             target="#editFoodModal">
                Edit
             </button>
      });
      domString += '</div></div>';
      utilities.printToDom('foodsModule', domString);
    })
    .catch((error) => console.error(error));
};

export default { createFoodCards };
```
* create an If statement in the function above so if the user object is found with firebase.auth().currentUser, then add the edit and delete buttons to the domstring. use this snippet in `createFoodCards`:
```
const user = firebase.auth().currentUser;
if (user != null) {
 // do stuff
}
```
* then import and call the `createFoodCards` function inside your init function of main.js
* the cards should ideally be styled using the bootstrap grid system to look something along the lines of the image below
<img width="520" alt="nutshellPostClose" src="https://user-images.githubusercontent.com/54124397/68959740-49077080-0794-11ea-877c-b423a15dc15f.PNG">

**Comment by michaelclark2** [comment]
I don't think the radio button will be necessary after the other comments, and think about how the food details will be displayed in each food card.
