### ISSUE TITLE
Food Service-Seed Data

### ISSUE THREAD

**Issue by ghost** [nss-evening-cohort-10/nutshell-panam-airlines#26]
# User Story
As a developer, I need to link my placeholder data to firebase and pull from firebase when the application is deployed.

# AC
**WHEN** the developer looks in firebase console
**THEN** they see a collection called food, and it contains food objects formatted in the style of the image below

# Dev Notes
* create a food.json file where you will create multiple (8 to start) food objects that look like this:
<img width="74" alt="nutshellFoodServiceERD" src="https://user-images.githubusercontent.com/54124397/68797779-ce671580-061a-11ea-8bcd-b95098760481.PNG">
* pull seed data into firebase in the Data section under the Database category

**Comment by michaelclark2** [comment]
I would keep the seed data to primarily just writing the json files and uploading them to the correct location in firebase.  so the AC would only be when the developer looks in firebase console, then they see a collection called food, and it contains objects that look like this. example
