### ISSUE TITLE
Food Service-Create

### ISSUE THREAD

**Issue by ghost** [nss-evening-cohort-10/nutshell-panam-airlines#27]
# User Story
As a user, I should be able to add items to the menu.

# AC 
**GIVEN** the user is logged in and visits the Crew page
**WHEN** a user pulls up the Food Service component
**THEN** they should see a Food Selection div where all the food options and details are listed
**AND** on centered over the Food Seleciton div will be an "Add New Food" button
**THEN** when they click the button, a modal pops up where you can enter the new food details
**AND** upon completing the form and clicking an "Add to Menu" button in the modal, the new food will be added to the seed data and subsequently print a corresponding new food card alongside the other existing cards

# Dev Notes
* create function in foodData.js in your data folder that will use `axios.post` to update your Firebase database with a new food item:

```
import axios from 'axios';
import apiKeys from '../apiKeys.json';

const baseUrl = apiKeys.firebaseKeys.databaseURL;

const addNewFood = (newFood) => axios.post(`${baseUrl}/foods.json`, newFood);

export default { addNewFood }
```

* this `addNewSnack` function will then be imported and called in  foodService.js under the function `const addNewFood`:
```
const addNewFood = (e) => {
  e.stopImmediatePropagation();
  const newPin = {
    name: $('#modal-name').val(),
    imageURL: $('#modal-image-url').val(),
    price: $('#modal-price').val(),
    category: $('#modal-category').val(),
    calories: `${'#modal-calories}.val()`,
  };
  foodData.addNewFood(newFood)
    .then(() => {
      $('#addFoodModal').modal('hide');
      // eslint-disable-next-line no-use-before-define
      foodPrinter.createFoodCards();
    })
    .catch((error) => console.error(error));
};
```

* `addNewFood` will be exported to be called later in an event listener
* this event listener will be attached to the unique id for the Submit button on the New Food modal that pops up after clicking the "Add New Food" button, and will add the new food input values (targeted by the values of each input in the  modal) as a new object in Firebase, and then call the `createFoodCards` function to reprint the food cards
* create an "Add New Food" bootstrap button in your `createFoodCards` function, and center the button above the main div where the food data is printed (as illustrated in the image below). This "Add New Food" button will be targeted by it's `id` for use with an event listener 
* upon click of the "Add New Food" button, the placeholder modal hardcoded in index.html should pop up with input fields for a new food object's key/value pairs matching the key value pairs in foods.json. You will create a function that prints the key value pairs of your food object to that modal, along with a "submit" button at the bottom of the modal.
* Attach a `click.` event listener to the submit button, that calls a function that will target the input values of the new food data ie. ` const modalForm =$('#myInput').val()` , and add them to Firebase via an `axios.post call`, and then re-call the original function you used to print the food items to the div while making sure the new item shows.
<img width="309" alt="nutshellCreate" src="https://user-images.githubusercontent.com/54124397/68915096-5be35c00-0726-11ea-98f1-cccc61e8d044.PNG">

**Comment by michaelclark2** [comment]
Let's rewrite this ticket to only be adding a new food item to the database, instead of adding a food item to a menu.
