### ISSUE TITLE
Food Service-Update

### ISSUE THREAD

**Issue by ghost** [nss-evening-cohort-10/nutshell-panam-airlines#28]
# User Story
As a user, I should be able to edit items on the menu.

# AC
**GIVEN** the user is logged in and visits the Crew Member page
**WHEN** the user pulls up the food service component
**THEN** they should see an "Edit" button on the bottom left corner of the main div where the food details are printing
**AND** when they click the "Edit" button
**THEN** a modal will appear where they can enter the new food details
**AND** the key value pairs for your food item will be printed to the modal as labels for an input form where the user will enter the new food details
**THEN** when the user clicks the "submit" button, the details for the selected item (via the values of the input form) will be updated in the Firebase data and on the module itself
**AND** your foods will be reprinted

# Dev Notes
* create a function in foodData.js that will update the image, name, price, calories, and menuCategory of the food to Firebase with an `axios.put` function, along the lines of:
```
const editFood = (foodId, editedFood) => axios.put(`${baseUrl}/foods/${foodId}.json`, editedFood);

export default { editFood };
 ```
* then import the `editFood` function listed above and create a new function in foodService.js to edit the selected pin and will pass through `editFood`. 
* To prepopulate the form in the modal, use the `getFood` function from foodData.js, and take the foodId as a parameter and resolves one single Food object
* After the form is edited with the new food info, update the dom in the .then using createFoodCards function
* Based on the values the user types in the input form of the  pop up modal after clicking the bootstrap "Edit" button on the selected food card. These values will be referenced as jquery objects that will grab each input value based on id, something along the lines of the following code:
```
import foodEditor from '../helpers/data/foodData.js'

const updateFood = (e) => {
  const editedFoodId = e.target.currentTarget.id;
  const editedFood = {
    imageURL: $('#edit-food-image-url').val(),
    name: $('#edit-food-name').val(),
    price: $('#edit-food-price').val(),
    calories: $('#edit-food-calories').val(),
    menuCategory: $('#edit-menu-category).val(),
  };
  foodData.editFood(editedFoodId, editedFood)
    .then(() => {
      $('#editFoodModal').modal('hide');
      // eslint-disable-next-line no-use-before-define
     createFoodCards();
    })
    .catch((error) => console.error(error));
};

export default
```
* create an event listener in foodService.js , that will be called inside `createFoodCards`. On click of the "Submit" button in the pop-up modal targeted by id or class:
`$(document.body).on('click', '#submitEditedFood', updateFood);`
<img width="207" alt="nutshellUpdate" src="https://user-images.githubusercontent.com/54124397/68963640-05fdcb00-079d-11ea-883c-a82a8d897f6f.PNG">

**Comment by michaelclark2** [comment]
I want to edit all the information about the food, not just the price
