### ISSUE TITLE
Food Service-Delete

### ISSUE THREAD

**Issue by ghost** [nss-evening-cohort-10/nutshell-panam-airlines#29]
# User Story
As a user, I should be able to delete items on the menu.

# AC
**GIVEN** the user is logged in and visits the Food Service page
**WHEN** a user clicks the "X" button in the top right of a food card
**THEN** that food's info should be removed from the Firebase database, and the food should be reprinted on the page

# Dev Notes
* in foodData.js create a function that deletes the foodId passed through it, from the Firebase data using an axios.delete call:

```
const deleteFood = (id) => axios.delete(`${baseUrl}/foods/${id}.json`);

export default { deletePin };
```

* then create a function in foodService.js that passes through the `deletePin` function mentioned above that targets the id of the card where the Close button was clicked. The function should target the foodID declared in "X" button on the food Card, call the firebase function to delete the selected info from your database, and call the function that reprints your food cards after updating the database.
* Call createFoodCards to update the dom when the delete is successful in the .then of the deleteCrewCard call:

```
const deleteFoodCard = (e) => {
  e.preventDefault();
  foodData.deletePin(e.target.id)
    .then(() => {
    // eslint-disable-next-line no-use-before-define
      console.log(e.target);
      foodPrinter.createFoodCards();
    })
    .catch((error) => console.error(error));
};
```

* Then call an event listener attached to the "x" aka close button in the top right corner of each food card, and upon click call the `deleteFoodCard` function. The event listener will be called in authData.js after login so only authorized users can modify the data
`$(document.body).on('click', '.delete-food', deleteFoodCard);`

<img width="517" alt="nutshellClose" src="https://user-images.githubusercontent.com/54124397/68914505-6997e200-0724-11ea-903d-55d6f62affec.PNG">
<img width="520" alt="nutshellPostClose" src="https://user-images.githubusercontent.com/54124397/68914513-70bef000-0724-11ea-9dab-dc2bf8f60e92.PNG">

**Comment by michaelclark2** [comment]
the last point in your dev notes should be reprinting the foods after modifying the data, you should not manipulate the dom directly
