### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by ghost** [nss-evening-cohort-10/nutshell-panam-airlines#30]
# User Story
As a user, I should be able to login and logout using Google.

# AC
**GIVEN** the user is not logged in
**WHEN** the user visits a page
**THEN** the login button should be in the navbar
**AND** when they press the button, the google signin popup should appear

**GIVEN** the user is logged in
**WHEN** the user visits a page
**THEN** the logout button should be in the navbar
**AND** when they press the button, the user should be signed out 
**AND** the user should be redirected to the home page

# Dev Notes
* Go to firebase and create a  new project for your application and register it, so you can receive the keys for the firebase. They should look  similar to the following object and key value pairs, and you will create an apiKeys.example.json in your data folder under helpers, so not anybody has access to your keys when you push up your code:
```
{
  "firebaseKeys" : {
    "apiKey": "",
    "authDomain": "",
    "databaseURL": "",
    "projectId": "",
    "storageBucket": "",
    "messagingSenderId": "",
    "appId": ""
  }
}
```
* inside the Data folder under Helpers, you will create an apiKeys.json to hold your actual keys, and then add the apiKeys.json file to your gitignore so you don't accidentally push up your apiKeys to github for someone to easily access. Then you'll pass these keys through an auth function given by firebase of your application upon authentication:
`import firebase from 'firebase';` in your main.js file first, then call the function given by firebase in your main init function:
```
const init = () => {
  firebase.initializeApp(apiKeys.firebaseKeys);
};

init();
```
* create an Auth folder, and auth.js file where you'll write a logMeIn function that uses the firebase.auth method to authenticate the user after importing firebase:
```
import firebase from 'firebase/app';
import 'firebase/auth';

const signMeIn = () => {
  const provider = new firebase.auth.GoogleAuthProvider();
  firebase.auth().signInWithPopup(provider);
};
```

* in auth.js  `import utilities from '../../helpers/utilities';` and also create a `const loginButton` eventlistener that will call the `signMeIn` function attached to an event listener targeting the Google login button by id on `.click(loginButton);`. Create this button in index.html by hardcoding it into the navbar.

* `export default ( attachEvents };` to be imported and called in main.js within the `const init {};` function
<img width="277" alt="nutshellAuth" src="https://user-images.githubusercontent.com/54124397/68892862-8662f400-06e9-11ea-874a-6ce17655c63d.PNG">
* After logging in via authentication, the user should be able to see and edit all components within the modules, but first they have to select the module they'd like to interact with on the dropdown (which will call an event listener created later to show the divs of the selected module and hide the divs other modules are printed to)
<img width="279" alt="nutshellLoginHome" src="https://user-images.githubusercontent.com/54124397/68893294-74ce1c00-06ea-11ea-8ce6-cd3bd3c08dc1.PNG">
<img width="276" alt="nutshellFoodServiceClick" src="https://user-images.githubusercontent.com/54124397/68893316-7f88b100-06ea-11ea-9fa3-658217fe7032.PNG">

* in the components folder, create a Navbar folder, with navbar.js and navbar.scss files. In navbar.js write an event listener for the logout button that will call a firebase.auth function which will register the logout event upon click of the logout button (targeted by id): similar to the format below:

```
import firebase from 'firebase/app';
import 'firebase/auth';

const logoutButton =('#insertLogoutButtonDivIdHere);



const attachEvents = () => {
  logoutButton.click((e) => {
    e.preventDefault();
    firebase.auth().signOut()
      .then(() => {
    // 
      }).catch((err) => console.error('you still logged in', err));
  });
  loginButton.click((e) => {
    // do stuff
  });
};

export default { attachEvents };
```
* `attachEvents` will then be imported and called in the `init` function in main.js

* first import firebase and jquery, then define the divs you'd like to hide or show by creating jQuery objects by targeting the selected divs by id or class. The divs you'll be targeting are the login/logout button that will display depending on the user's authentication state. Then call an `if else` statement that will `hide` the logout button upon logout, and show the login button, and vice versa in a manner similar to the code outlined below:

```
import $ from 'jquery';
import firebase from 'firebase/app';
import 'firebase/auth';

const logoutNavbar = $('#navbar-button-logout');
const loginNavbare = 

const checkLoginStatus = () => {
  firebase.auth().onAuthStateChanged((user) => {
    if (user) {
      // someone is logged in - we should see logout button
      logoutNavbar.removeClass('hide');
    } else {
      // nobody logged in - SHOW login button
 
      logoutNavbar.addClass('hide');
    }
  });
};

export default { checkLoginStatus };
```
* call your exported `checkLoginStatus` in main.js within your `init` function
* to see if you can login using your Google credentials on click of the login button, and check to make sure Firebase recognized you as a unique authenticated user

**Comment by michaelclark2** [comment]
Talk more about how the login and logout button will appear on the page and how you will show and hide the components that can allow you to edit/delete/create new items

**Comment by michaelclark2** [comment]
The only thing i would advise against is creating a function that will print the login/logout button.  I think you can just hardcode them into the navbar, then use the onAuthStateChanged to hide/show the proper button.  Make that small change and this ticket is perfect
