### ISSUE TITLE
Setup Files

### ISSUE THREAD

**Issue by ghost** [nss-evening-cohort-10/nutshell-panam-airlines#31]
# User Story
As a developer I need to create my boilerplate setup files to get started on my project

# AC
**WHEN** I view the project
**THEN** I should see bootstrap button
**AND** there should be a background color from styles/main.scss
**AND** there should be a console.log from main.js

# Dev Notes
* Follow guidelines from: https://github.com/nss-nightclass-projects/Night-Class-Resources/blob/master/book-2-patterns-and-tools/chapters/task-runners.md
* hardcode bootstrap modal in index.html that all modules will use to print their CRUD components to
* create base.json file to outline all module collections

**Comment by michaelclark2** [comment]
base.json

```
{
  "airports" : "",
  "planes" : "",
  "crew" : "",
  "food" : "",
  "baggage" : ""
}
```
