### ISSUE TITLE
Airport seed-data

### ISSUE THREAD

**Issue by John-Ryan-Johnson** [nss-evening-cohort-10/nutshell-panam-airlines#32]
**Story**
As a developer, I need some data in order to start coding

**AC**

WHEN I login to firebase and look at the database
THEN I should see 10 objects that look like the example in dev notes
AND there should be a airports.json file in the db folder

**Dev Notes**

{
"airports": {
     "image": "",
     "name": "",
     "location": "",
    "isInternational": "true"
   },
}

**Comment by michaelclark2** [comment]
I would put a quick example of how you want an airport object to look like, try and reference the ERD to create a dummy airport object so you can reference it when you start making them

**Comment by michaelclark2** [comment]
Your acceptance criteria should include what your collection is gonna be called in firebase and how many objects you are going to create
