### ISSUE TITLE
Crew Member - Wireframe

### ISSUE THREAD

**Issue by rtate2** [nss-evening-cohort-10/nutshell-panam-airlines#34]
# User Story
As a user, you will be able to click on the navbar's dropdown menu and select "Crew" to view the professional staff

**Crew Home View**
<img width="531" alt="PanAm-Crew-allCards" src="https://user-images.githubusercontent.com/54008854/68985030-3b280e80-07d9-11ea-89a2-75ffffa1fca3.png">

**Comment by michaelclark2** [comment]
Lets keep all the crew on one page instead of breaking up the crew members into two views.  I would like to see the profile cards have the crew members job position instead of separating pilots from cabin crew.
