### ISSUE TITLE
Part 2: Menu - Seed Data

### ISSUE THREAD

**Issue by EmileeA** [nss-evening-cohort-10/nutshell-panam-airlines#76]
# User Story

As a developer, I should be able to look at the `menu.json` and see the structure needed to extract data.

# AC

**WHEN** I look at the JSON
**THEN** I should see a data structure 
**AND** data filled in.

# Dev Notes

* This fulfills the seed data needed to meet the `READ` requirements of this project.

* Requirements:
 -If a flight is less than 6 hours, only provide snacks as menu options
 -If a flight is more than 6 hours, meals and snacks should be provided as menu options

1. Data structure:

* the data structure will look as follows:

```
{
  "id": "menu1",
   "name": "Day Menu",
  "isLong": "true",
  "foodItemId": "3978650",
  "foodItemId": "2348701",
}
```

* create `menu.json` for seed data in the `db` folder of the project
* create 4 snack options, and 4 meal options following the above structure format

* import this data into firebase

2. Helpers and files/retrieving from firebase:

* create a `menuData.js` file in the `javascripts/helpers/data` to pull the JSON data from firebase

*the first 4 lines of code at the top of the file are:

```
import axios from 'axios';
import apiKeys from '../apiKeys.json';
import 'firebase/auth';

const baseUrl = apiKeys.firebaseKeys.databaseURL;
```

* the function to pull this data down requires an axios.get(). It should look something like this:

```
const menusDataByFlightId = (flightId) => new Promise((resolve, reject) => {
  axios.get(`${baseUrl}/menus.json?orderBy="flightId"&equalTo="${flightId}"`)
    .then((response) => {
      const demMenus = response.data;
      const menus= [];
      Object.keys(demMenus).forEach((ftId) => {
        demMenus[ftId].id = ftId;
        menus.push(demMenuss[ftId]);
      });
      resolve(menus);
    })
    .catch((error) => reject(error));
});
```

3. Components folders and files:

* create a `Menu` folder inside `javascripts/components` and place four files within it: `menus.js`, `menus.scss`, `menuFunctions.js`, and `menuFinalActions.js`

* link the menus.scss file to the menus.js by placing this line at the top of your menus.js:

`import './menus.scss';`

* at the bottom of `menus.js`, place this line:

`export default { displayMenu };`

* inside your `main.js`, at the top of the page, place this line:

`import menuDisplay from './components/Menus/menus';`

*and, within the init function, place this line:

`menuDisplay .displayMenu();`

* within `menuFunctions.js`, place this line at the top:

import `menuDisplay` from '.menus';

4. Printing the data to the DOM

* the menus.js file will contain a function called `displayMenu` that prints to a menus div on index.html when the tab for Menu's is selected on the Food Service page

* `displayMenu` will display the item name, and if the item is a snack or not, along with button allowing editing of the item, and a button allowing deletion of the item all housed within a card (see Bootstrap link below for card)

* at the top of this page, there should be a button that allows the user to create a new menu item; see wireframe for clarification; dynamically print this with displayMenu or toggle a hide when not viewing

* ideally, utilize bootstrap cards to achieve what the wireframe advertises. as far as color of the cards, you may have to adopt the source code of the cards in your employees.scss and modify it. the bootstrap source code can be found here: https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css

**Comment by mariabrock** [comment]
https://getbootstrap.com/docs/4.4/components/card/#titles-text-and-links
