### ISSUE TITLE
Crew Member - Read

### ISSUE THREAD

**Issue by rtate2** [nss-evening-cohort-10/nutshell-panam-airlines#8]
# User Story
As a user, I should be able to view all crew members on the team.

# Acceptance Criteria
**WHEN** the user visits the Crew page
**THEN** they will be able to see all of the crew members
**AND** there will be 2 in a row, and they will follow the mockups

# Dev Notes

1. If the userobject is found with `firebase.auth().currentUser`, then add the edit and delete buttons to the domstring. use this snippet in createCrewCard
```
const user = firebase.auth().currentUser;
if (user != null) {
 // do stuff
}
```

1. Create crewData.js in javascripts/helpers/data and create an axios call getAllCrewMembers promise to get the data imported and turn object of arrays to an array - see seed data ticket for example object #41 

1. Create crew folder component within javascripts/components and include crew.js and crew.scss, be sure to link the js and scss
   i). In crew.js create a createCrewCard function that calls the getAllCrewMembers and runs it through a forEach loop and create bootstrap cards; this will print out to the ```crew div``` within the html - this will be printed to the DOM upon page load using printToDom

1. **Styling** 
   • "Flight Crew" centered as H1 tag on page Load
   • Background image of PanAm image which spans the entire screen
   • Cards spaced evenly centered in the page under the title, maximum of three per row

**Comment by michaelclark2** [comment]
This is a pretty good ticket,  I would remove the crewCategory component and find a way for the crewIndividual card to display the job that the crew member is assigned

**Comment by rtate2** [comment]
**Individual Crew Member Wireframe**
<img width="297" alt="PanAm-Crew-singleCardView" src="https://user-images.githubusercontent.com/54008854/68984506-15e5d100-07d6-11ea-9ee9-079f8825cb62.png">
