### ISSUE TITLE
Crew Member -Create

### ISSUE THREAD

**Issue by rtate2** [nss-evening-cohort-10/nutshell-panam-airlines#9]
# User Story
As a user, I should be able to add a crew member to the team.

# Acceptance Criteria
**GIVEN** the user is logged in and visits the Crew page
**WHEN** they click the "Add Employee" button
**THEN** there will be a modal to create a new crew member
<img width="230" alt="PanAm-Crew-Modal" src="https://user-images.githubusercontent.com/54008854/68985811-f010fa00-07de-11ea-8bd2-6bc13620773c.png">

**WHEN** the "save" button is clicked
**THEN** the new user will be found in crew collection in firebase
**AND** the dom will be updated from firebase

# Dev Notes
• Create an axios call in the crewData.js (addNewMember) file that allows user to post the object to firebase (post) 
- addNewMember will take a crew member object as a parameter

• Create a button below the title that creates a modal for the user to input information to create a new employee within the specific category
• Create addCrewMember function within components/Crew/crew.js that reads the values from the input fields to create a new crewMember object, and then pass the object to addNewMember
• update dom with createCrewMembers function

Styling
• The card styling will be the same within a bootstrap card

**Comment by rtate2** [comment]
**Full Page View w/ Modal example**
<img width="807" alt="Screen Shot 2019-11-18 at 8 23 16 PM" src="https://user-images.githubusercontent.com/54008854/69110776-54cb8f00-0a41-11ea-84f3-e68befde92be.png">

**Comment by michaelclark2** [comment]
The acceptance criteria should include how the form is presented to the user.  You say there is a modal, but how do I fire it off and what does it look like?  
Also, your last bullet point in the dev notes is not what you should achieve.  you should send the values from the input fields to firebase, then use the same function you made to print the cards from firebase.  do not manipulate the dom directly without pulling from firebase.
